name: 'Build the Java Application'
description: 'Build the Java Application'

inputs:
  github-token:
    description: 'The github token'
    required: true
  sonar-token:
    description: 'The sonar token'
    required: true

runs:
  using: 'composite'
  steps:
#    Every shell step in a composite action MUST explicitly define the shell
  - name: Checkout
    uses: actions/checkout@v4
  - name: Download Build Artefact
    uses: actions/download-artifact@v4
    with:
      name: build
      path: .
  - name: Cache Dependency-Check data
    uses: actions/cache@v4
    with:
      path: ~/.cache/dependency-check
      key: odc-${{ runner.os }}-12.2.2-${{ hashFiles('**/gradle.lockfile', '**/build.gradle', '**/settings.gradle') }}
      restore-keys: |
        odc-${{ runner.os }}-12.2.2-
  - name: Cache Gradle and Maven
    uses: actions/cache@v4
    with:
      path: |
        ~/.gradle/caches
        ~/.gradle/wrapper
        ~/.m2/repository
      key: ${{ runner.os }}-deps-${{ hashFiles('**/*.gradle*', '**/gradle.lockfile', '**/settings.gradle*') }}
  - name: Run Gradle DependencyCheckAnalyse 
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      NODE_TLS_REJECT_UNAUTHORIZED: "0" 
      SONAR_HOST_URL: "http://10.0.2.15:9300"
#        run: gradle clean build test jacocoTestReport jacocoTestCoverageVerification sonar cyclonedxBom dependencies -info --scan -PignoreFailures=true --write-locks --continue
    run: ./gradlew build -x dependencies dependencyCheckAnalyze -info --scan --write-locks
  - name: Publish Report
    uses: actions/upload-artifact@master
    with:
        name: Depcheck report
        path: build/reports/dependency-check/dependency-check-report.html
        retention-days: 1
  - uses: tiacsys/clean-after-action@v3