name: 'Dependency Check Analysis'
description: 'Dependency Check Analysis'

inputs:
  github-token:
    description: 'The github token'
    required: true

runs:
  using: 'composite'
  steps:
#    Every shell step in a composite action MUST explicitly define the shell
  - name: Checkout
    uses: actions/checkout@v6
  - name: Download Build Artefact
    uses: actions/download-artifact@v8
    with:
      name: build
      path: .
  - name: Cache Dependency-Check data
    uses: actions/cache@v5
    with:
      path: ${{ runner.home }}/.cache/dependency-check
      key: odc-${{ runner.os }}-12.2.2-${{ hashFiles('**/gradle.lockfile', '**/build.gradle', '**/settings.gradle') }}
      restore-keys: |
        odc-${{ runner.os }}-12.2.2-
  - name: Cache Gradle and Maven
    uses: actions/cache@v5
    with:
      path: |
        ${{ runner.home }}/.gradle/caches
        ${{ runner.home }}/.gradle/wrapper
        ${{ runner.home }}/.m2/repository
      key: ${{ runner.os }}-gradle-deps-${{ hashFiles('**/*.gradle*', '**/gradle.lockfile', '**/settings.gradle*') }}
  - name: Run Gradle DependencyCheckAnalyse 
    env:
      GITHUB_TOKEN: ${{ inputs.github-token }}  
      NODE_TLS_REJECT_UNAUTHORIZED: "0" 
#        run: gradle clean build test jacocoTestReport jacocoTestCoverageVerification sonar cyclonedxBom dependencies -info --scan -PignoreFailures=true --write-locks --continue
    run: ./gradlew build dependencies dependencyCheckAnalyze -info --scan --write-locks -x test
    shell: bash 
  - name: Publish Report
    uses: actions/upload-artifact@master
    with:
        name: Depcheck report
        path: build/reports/dependency-check/dependency-check-report.html
        retention-days: 1
  - uses: tiacsys/clean-after-action@v4