#!/usr/bin/env bash
set -euo pipefail

: "${GH_TOKEN:?GH_TOKEN is required}"
: "${GH_REPO:?GH_REPO is required}"
: "${PR_NUMBER:?PR_NUMBER is required}"
: "${RUN_URL:?RUN_URL is required}"

MARKER="<!-- spotbugs-findsecbugs-summary -->"
SUMMARY_FILE="build/reports/spotbugs/main/spotbugs-summary.md"

if [[ -f "$SUMMARY_FILE" ]]; then
  REPORT="$(cat "$SUMMARY_FILE")"
else
  REPORT=$'## SpotBugs / FindSecBugs Security Summary\n\nReport unavailable.'
fi

BODY="$(
  {
    printf '%s\n' "$MARKER"
    printf '%s\n' "$REPORT"
    printf '\n'
    printf '**Workflow run:** [View latest SpotBugs run](%s)\n' "$RUN_URL"
    printf '\n'
    printf '%s\n' '_Generated by SpotBugs + FindSecBugs. This comment is updated on every PR pipeline run._'
  }
)"

EXISTING_COMMENT_ID="$(
  gh api \
    --paginate \
    "/repos/${GH_REPO}/issues/${PR_NUMBER}/comments?per_page=100" \
    --jq ".[] | select(.body | contains(\"${MARKER}\")) | .id" \
    | head -n 1
)"

if [[ -n "$EXISTING_COMMENT_ID" ]]; then
  echo "Updating SpotBugs PR summary comment ${EXISTING_COMMENT_ID}."
  gh api \
    --method PATCH \
    "/repos/${GH_REPO}/issues/comments/${EXISTING_COMMENT_ID}" \
    -f body="$BODY"
else
  echo "Creating SpotBugs PR summary comment."
  gh api \
    --method POST \
    "/repos/${GH_REPO}/issues/${PR_NUMBER}/comments" \
    -f body="$BODY"
fi
