name: 'Secrets Scan'
description: 'Secrets Scan'

inputs:
  github-token:
    description: 'The github token'
    required: true

runs:
  using: 'composite'
  steps:
      - name: Git Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Download Build Artefact
        uses: actions/download-artifact@v8
        with:
          name: build
          path: .
      - name: Gitleaks
        id: gitleaks
        continue-on-error: true
        uses: frankbuttigieg1993-gmail/cicd/.github/actions/gitleaks@main
        with:
          github-token: ${{ inputs.github-token }}
      - name: Trivy Secrets Scan
        id: trivy
        uses: frankbuttigieg1993-gmail/cicd/.github/actions/trivy-secrets-scan@main
        continue-on-error: true
        with:
          github-token: ${{ inputs.github-token }}
      - name: Publish Secrets Scan Reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v7
        with:
          name: secrets-scan-reports 
          path: |
            build/reports/trivy-secrets/
            build/reports/gitleaks/
          retention-days: 2
          if-no-files-found: warn