name: 'Secrets Scan'
description: 'Secrets Scan'

inputs:
  github-token:
    description: 'The github token'
    required: true

runs:
  using: 'composite'
  steps:
      - name: Git Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Download Build Artefact
        uses: actions/download-artifact@v8
        with:
          name: build
          path: .
      - name: Gitleaks
        id: gitleaks
        continue-on-error: true
        uses: frankbuttigieg1993-gmail/cicd/.github/actions/gitleaks@main
        with:
          github-token: ${{ inputs.GITHUB_TOKEN }}
      - name: Trivy Secrets Scan
        id: trivy
        continue-on-error: true
        uses: frankbuttigieg1993-gmail/cicd/.github/actions/trivy-secrets-scan@main
        with:
          github-token: ${{ inputs.GITHUB_TOKEN }}
      - name: Publish Secrets Scan Reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v7
        with:
          name: secrets-scan-reports 
          path: |
            build/reports/trivy-secrets/
            build/reports/gitleaks/
          retention-days: 2
          if-no-files-found: warn
      - name: Check Secrets Scan Results
        if: always()
        shell: bash
        run: |
          echo "Gitleaks result: ${{ steps.gitleaks.outcome }}"
          echo "Trivy result:    ${{ steps.trivy.outcome }}"

          if [[ "${{ steps.gitleaks.outcome }}" != "success" ]] || [[ "${{ steps.trivy.outcome }}" != "success" ]]; then
            echo "::error::One or more secret scanners failed."
            exit 1
          fi