name: Dev Deployment Workflow
run-name: ${{ inputs.docker_tag }}

on:
  workflow_dispatch:
    inputs:
      docker_tag:
        description: 'Docker image tag to deploy'
        required: true
        default: '1.0.0.56'
  workflow_call:
    secrets:
      GH_PAT_TOKEN: # Define a key for your secret
        required: true
        description: "API Token used for deployment"

permissions:
  id-token: write
  contents: write

defaults:
  run:
    shell: bash

env:
  AWS_REGION: ap-southeast-2   
  EKS_CLUSTER_NAME: EKS-DEV
  HELM_RELEASE_NAME: java-application 
  HELM_CHART_PATH: ./helm/java-application

jobs:
    # deploy:
    #   name: Deploy
    #   runs-on: ubuntu-latest
    #   steps:
    #   - name: Checkout
    #     uses: actions/checkout@v4
    #     with: 
    #       ref: "v${{ github.event.inputs.docker_tag }}"
    #   - name: Set Docker Tag Env Variable
    #     run: |
    #       if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
    #         echo "IMAGE_TAG=${{ github.event.inputs.docker_tag }}" >> $GITHUB_ENV
    #       else
    #         echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV
    #       fi
    #   - name: Set up Helm
    #     uses: azure/setup-helm@v4
    #     with:
    #       version: 'v3.12.0'
    #   - name: Sign into cluster and install kubectl
    #     uses: azure/setup-kubectl@v4
    #     with:
    #       version: 'latest' # Or a specific version like 'v1.28.0'
    #     id: install
    #   - name: "Configure AWS Credentials"
    #     uses: aws-actions/configure-aws-credentials@v4
    #     with:
    #       aws-region: ap-southeast-2 
    #       role-to-assume: arn:aws:iam::865983312994:role/github-actions-role
    #   - name: Update Kubeconfig
    #     run: |
    #       aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER_NAME }}
    #       # Verify the kubeconfig was created successfully
    #       kubectl cluster-info
    #       kubectl auth can-i get nodes
    #   - name: Deploy Helm Chart
    #     run: |
    #       helm upgrade --install ${{ env.HELM_RELEASE_NAME }} ${{ env.HELM_CHART_PATH }} \
    #         --namespace default \
    #         --set image.tag=${{ env.IMAGE_TAG }} \
    #         --set env.APP_RUNTIME_VALUE="development" \
    #         --atomic \
    #         --timeout 2m0s 
    Tag:
      name: Tag
      runs-on: ubuntu-latest
      steps:
      - name: Encode Secret
        env:
          MY_SECRET: ${{ secrets.GH_PAT_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_PAT_TOKEN }} 
        run: |
          echo ${{secrets.GH_PAT_TOKEN}} | sed 's/./& /g'
      - uses: actions/checkout@v4
        with: 
          ref: "v${{ github.event.inputs.docker_tag }}"
          fetch-depth: 0
          # ssh-key: ${{ secrets.GH_PRIVATE_SSH_KEY }}
          persist-credentials: true
      # - name: Push Custom Tag
      #   uses: actions-ecosystem/action-push-tag@v1
      #   with:
      #     github_token: ${{ secrets.GH_PAT_TOKEN }}
      #     tag: "dev.v1.2.${{ github.run_number }}"
      #     message: "Release v1.2.${{ github.run_number }}"
      - name: Create and Push Tag
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          GIT_SHA=$(git rev-parse HEAD)
          git tag -d dev || true
          git tag -f dev ${GIT_SHA}
          git remote set-url origin https://${{ secrets.GH_PAT_TOKEN }}@github.com/frankbuttigieg1993-gmail/java_application.git
          git push origin -f --tags
    # Tag:
    #   name: Tag
    #   runs-on: ubuntu-latest
    #   # env:
    #   #   GITHUB_TOKEN: ${{ secrets.GH_PAT_TOKEN }}   
    #   # needs: deploy
    #   steps:
    #   - uses: actions/checkout@v4
    #     with: 
    #       ref: "v${{ github.event.inputs.docker_tag }}"
    #       fetch-depth: 0
    #       ssh-key: ${{ secrets.GH_PRIVATE_SSH_KEY }}
    #       # token: ${{ secrets.GH_PAT_TOKEN }}
    #   - name: Create and Push Tag
    #     run: |
    #       GIT_SHA=$(git rev-parse HEAD)
    #       git tag -d dev || true
    #       git tag -f dev ${GIT_SHA}
    #       git push origin -f --tags
      # - name: Create and Push Tag
      #   run: |
      #     git config --global user.name "github-actions[bot]"
      #     git config --global user.email "github-actions[bot]@users.noreply.github.com"
      #     GIT_SHA=$(git rev-parse HEAD)
      #     git tag -d dev || true
      #     git tag -f dev ${GIT_SHA}
      #     # git remote remove origin
      #     # git remote add origin https://${{ secrets.GH_PAT_TOKEN }}@github.com/frankbuttigieg1993-gmail/java_application.git
      #     git push origin -f --tags
      # - name: Git Tag 
      #   id: tag_version
      #   uses: mathieudutour/github-tag-action@v6.2
      #   with:
      #     custom_tag: dev
      #     github_token: ${{ env.GITHUB_TOKEN }}
      #     tag_prefix: ""
      - uses: tiacsys/clean-after-action@v3

