# Gradle executing the sonarqube scan is the recommended way for java projects. Running it via the build tool ensures that compiled .class binaries and test coverage reports (like JaCoCo) are properly recognized without requiring complex file mapping parameters
# https://stackoverflow.com/questions/77373748/unable-to-run-sonarqube-scan-for-my-java-repository-using-github-actions
# https://docs.sonarsource.com/sonarqube-server/10.8/devops-platform-integration/github-integration/adding-analysis-to-github-actions-workflow

name: Java Application - Scanning All
run-name: ${{ github.ref_name }}-${{ github.run_number }}

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      target-runner:
        required: true
        type: string
        
defaults:
  run:
    shell: bash

permissions:
  contents: write  # Required for checkout and write is required for tagging the git repository
  issues: write
  id-token: write # This is required for requesting the JWT for OIDC auth to AWS
  security-events: write # Required for Semgrep and Uploading to GitHub Security Feature

env:
  AWS_REGION: ap-southeast-2                   # set this to your preferred AWS region, e.g. us-west-1
  build-artifact-key: app-${{ github.sha }}
  ECR_REPOSITORY: java-application           # set this to your Amazon ECR repository name
  NODE_TLS_REJECT_UNAUTHORIZED: '0' # # Disables SSL strictness for Node tools - addresses trivy certificate issue behind CGI corporate proxy
  GIT_SSL_NO_VERIFY: 'true'           # temporarily disable git SSL verification
  

concurrency:
  group: ${{ github.workflow }}-runner-${{ github.ref }}
  cancel-in-progress: false

jobs:
    Build:
      name: Build
      runs-on: ${{ fromJson(inputs.target-runner) }} 
      outputs:
        APP_VERSION: ${{ steps.app_version.outputs.APP_VERSION }}
      steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set APP_VERSION Output 
        id: app_version
        run: echo "APP_VERSION=$(cat ./build.gradle | grep 'version =' | cut -d "=" -f 2 | tr -d "'" | xargs)" >> "$GITHUB_OUTPUT"
      - name: Java Build
        uses: frankbuttigieg1993-gmail/cicd/.github/actions/java/build@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}  
    test-code:
      name: Run Tests
      runs-on: ${{ fromJson(inputs.target-runner) }} 
      needs: Build
      env:
        NODE_TLS_REJECT_UNAUTHORIZED: '0'   # temporarily disable Node TLS checks
        GIT_SSL_NO_VERIFY: 'true'           # temporarily disable git SSL verification
      steps:
      - name: Java Test
        uses: frankbuttigieg1993-gmail/cicd/.github/actions/java/test@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}  
    sonar-scan:
        name: SonarQube Scan & Gate Check
        runs-on: ${{ fromJson(inputs.target-runner) }} 
        needs: test-code
        env:
          NODE_TLS_REJECT_UNAUTHORIZED: '0'   # temporarily disable Node TLS checks
          GIT_SSL_NO_VERIFY: 'true'           # temporarily disable git SSL verification
        steps:
          - name: Sonar Scan Java Application
            uses: frankbuttigieg1993-gmail/cicd/.github/actions/sonar-scan@main
            with:
              github-token: ${{ secrets.GITHUB_TOKEN }}  
              sonar-token: ${{ secrets.SONAR_TOKEN }} 
    DependencyCheck:
      name: DependencyCheck
      runs-on: ${{ fromJson(inputs.target-runner) }} 
      needs: Build
      steps:
      - name: Dependency Check
        uses: frankbuttigieg1993-gmail/cicd/.github/actions/dependency-check@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}  
    CycloneDX_SBOM:
      name: CycloneDX_SBOM
      runs-on: ${{ fromJson(inputs.target-runner) }} 
      needs: [Build]
      steps:
      - name: CycloneDX SBOM
        uses: frankbuttigieg1993-gmail/cicd/.github/actions/cyclone-dx-sbom@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}  
    Trivy:
      name: Trivy
      runs-on: ${{ fromJson(inputs.target-runner) }} 
      needs: [Build]
      env:
        NODE_TLS_REJECT_UNAUTHORIZED: "0" # Disables SSL strictness for Node tools - addresses trivy certificate issue behind CGI corporate proxy
        GIT_SSL_NO_VERIFY: "true"         # Disables SSL strictness for Git fetches
      steps:
      - name: Trivy Scan 
        uses: frankbuttigieg1993-gmail/cicd/.github/actions/trivy-scan@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}  
    semgrep_scan:
      name: semgrep/ci
      runs-on: ${{ fromJson(inputs.target-runner) }} 
      needs: [Build]
      env:
        SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }} 
        HOME: ${{ github.workspace }}    # Points Semgrep to the workspace directory it already has access to
      # Skip any PR created by dependabot to avoid permission issues:
      if: (github.actor != 'dependabot[bot]')
      steps:
      - name: Semgrep Scan 
        uses: frankbuttigieg1993-gmail/cicd/.github/actions/semgrep-scan@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}  
    Docker_Push:
      name: Docker Push
      runs-on: ${{ fromJson(inputs.target-runner) }} 
      needs: Build
      steps:
      - name: Docker Push 
        uses: frankbuttigieg1993-gmail/cicd/.github/actions/docker-push@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}  
    Tag:
      name: Tag
      runs-on: ubuntu-24.04
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
      needs: [Build, Docker_Push]
      steps:
      - uses: actions/checkout@v4
        with:
          clean: true
      - name: Git Tag 
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          release_branches: "release.*"
          github_token: ${{ env.GITHUB_TOKEN }}
          custom_tag: ${{ needs.Build.outputs.APP_VERSION }}.${{ github.run_number }}
      - uses: tiacsys/clean-after-action@v3