# Gradle executing the sonarqube scan is the recommended way for java projects. Running it via the build tool ensures that compiled .class binaries and test coverage reports (like JaCoCo) are properly recognized without requiring complex file mapping parameters
# https://stackoverflow.com/questions/77373748/unable-to-run-sonarqube-scan-for-my-java-repository-using-github-actions
# https://docs.sonarsource.com/sonarqube-server/10.8/devops-platform-integration/github-integration/adding-analysis-to-github-actions-workflow

name: Java Build Pipeline
run-name: ${{ github.ref_name }}-${{ github.run_number }}

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      target-runner:
        required: true
        type: string
        
defaults:
  run:
    shell: bash

permissions:
  contents: write  # Required for checkout and write is required for tagging the git repository
  id-token: write # This is required for requesting the JWT for OIDC auth to AWS
  security-events: write # Required for Semgrep and Uploading to GitHub Security Feature
  actions: write
  pull-requests: write
  issues: write
  statuses: write

env:
  AWS_REGION: ap-southeast-2
  ECR_REPOSITORY: java-application
  NODE_TLS_REJECT_UNAUTHORIZED: '0' # # Disables SSL strictness for Node tools - addresses trivy certificate issue behind CGI corporate proxy
  GIT_SSL_NO_VERIFY: 'true'           # temporarily disable git SSL verification
  

# concurrency:
#   group: ${{ github.workflow }}-runner-${{ github.ref }}
#   cancel-in-progress: false

jobs:
  Build:
    name: Build
    runs-on: ${{ fromJson(inputs.target-runner) }} 
    outputs:
     APP_VERSION: ${{ steps.java-build.outputs.APP_VERSION }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Java Build
      id: java-build
      uses: frankbuttigieg1993-gmail/cicd/.github/actions/java/build@main
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
  Unit_Tests:
    name: Unit_Tests
    runs-on: ubuntu-24.04
    needs: [Build]
    steps:
    - name: Java Test
      uses: frankbuttigieg1993-gmail/cicd/.github/actions/java/test@main
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }} 
  Secrets_Scan:
      name: Secrets Scan 
      runs-on: ${{ fromJson(inputs.target-runner) }} 
      needs: [Scans]
      steps:
      - name: Secrets Scan
        uses: frankbuttigieg1993-gmail/cicd/.github/actions/secrets-scan@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}  
  Scans:
    name: Scans
    runs-on: ${{ fromJson(inputs.target-runner) }} 
    needs: [Build]
    steps:
    - name: Scans
      run: | 
        echo "Executing Security Scans
      shell: bash
  Runtime_Vulnerability_Scan:
    name: Runtime Vulnerability Scan
    runs-on: ${{ fromJson(inputs.target-runner) }} 
    needs: [Scans]
    steps:
    - name: Runtime Vulnerability Scan
      uses: frankbuttigieg1993-gmail/cicd/.github/actions/runtime-vulnerability-scan@main
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}  
  SpotBugs:
    name: SpotBugs 
    runs-on: ubuntu-24.04
    needs: [Scans]
    env:
      NODE_TLS_REJECT_UNAUTHORIZED: "0" # Disables SSL strictness for Node tools - addresses trivy certificate issue behind CGI corporate proxy
      GIT_SSL_NO_VERIFY: "true"         # Disables SSL strictness for Git fetches
    steps:
    - name: SpotBugs 
      uses: frankbuttigieg1993-gmail/cicd/.github/actions/spotbugs@main
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
  SBOM_Generator:
    name: Generate SBOMs
    runs-on: ${{ fromJson(inputs.target-runner) }} 
    needs: [Build]
    steps:
    - name: Generate SBOMs
      uses: frankbuttigieg1993-gmail/cicd/.github/actions/sbom-generator@main
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}  
  semgrep_appsec_scan:
    name: Semgrep AppSec Scan 
    runs-on: ubuntu-24.04
    needs: [Scans]
    env:
      HOME: ${{ github.workspace }}    # Points Semgrep to the workspace directory it already has access to
    # Skip any PR created by dependabot to avoid permission issues:
    if: (github.actor != 'dependabot[bot]')
    steps:
    - name: Semgrep AppSec Scan 
      uses: frankbuttigieg1993-gmail/cicd/.github/actions/semgrep-appsec-scan@main
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }} 
        SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
  sonar-scan:
      name: SonarQube Scan & Gate Check
      runs-on: ${{ fromJson(inputs.target-runner) }} 
      needs: [Scans]
      env:
        NODE_TLS_REJECT_UNAUTHORIZED: '0'   # temporarily disable Node TLS checks
        GIT_SSL_NO_VERIFY: 'true'           # temporarily disable git SSL verification
      steps:
        - name: Sonar Scan Java Application
          uses: frankbuttigieg1993-gmail/cicd/.github/actions/sonar-scan@main
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}  
            sonar-token: ${{ secrets.SONAR_TOKEN }} 
  Trivy_Scan:
    name: Trivy Scan
    runs-on: ubuntu-24.04
    needs: [Scans]
    steps:
    - name: Trivy Scan 
      uses: frankbuttigieg1993-gmail/cicd/.github/actions/trivy-scan@main
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}   
  Docker_Push:
    name: Docker Push
    runs-on: ${{ fromJson(inputs.target-runner) }} 
    needs: [Build, Unit_Tests]
    steps:
    - name: Docker Push 
      uses: frankbuttigieg1993-gmail/cicd/.github/actions/docker-push@main
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
  Tag:
    name: Tag
    runs-on: ubuntu-24.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
    needs: [Build, Docker_Push]
    steps:
    - uses: actions/checkout@v4
      with:
        clean: true
    - name: Git Tag 
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.2
      with:
        release_branches: "release.*"
        github_token: ${{ env.GITHUB_TOKEN }}
        custom_tag: ${{ needs.Build.outputs.APP_VERSION }}.${{ github.run_number }}
    - uses: tiacsys/clean-after-action@v3
    # DependencyCheck:
    #   name: DependencyCheck
    #   runs-on: ubuntu-24.04
    #   needs: Build
    #   steps:
    #   - name: Dependency Check
    #     uses: frankbuttigieg1993-gmail/cicd/.github/actions/dependency-check@main
    #     with:
    #       github-token: ${{ secrets.GITHUB_TOKEN }} 