# Gradle executing the sonarqube scan is the recommended way for java projects. Running it via the build tool ensures that compiled .class binaries and test coverage reports (like JaCoCo) are properly recognized without requiring complex file mapping parameters
# https://stackoverflow.com/questions/77373748/unable-to-run-sonarqube-scan-for-my-java-repository-using-github-actions
# https://docs.sonarsource.com/sonarqube-server/10.8/devops-platform-integration/github-integration/adding-analysis-to-github-actions-workflow

name: Java Application - Sonarqube Gradle
run-name: ${{ github.ref_name }}-${{ github.run_number }}

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      target-runner:
        required: true
        type: string
        
defaults:
  run:
    shell: bash

env:
  AWS_REGION: ap-southeast-2                   # set this to your preferred AWS region, e.g. us-west-1
  build-artifact-key: app-${{ github.sha }}
  ECR_REPOSITORY: java-application           # set this to your Amazon ECR repository name

jobs:
    Build:
      name: Build
      runs-on: ${{ fromJson(inputs.target-runner) }} 
      outputs:
        APP_VERSION: ${{ steps.app_version.outputs.APP_VERSION }}
      env:
        NODE_TLS_REJECT_UNAUTHORIZED: '0'   # temporarily disable Node TLS checks
        GIT_SSL_NO_VERIFY: 'true'           # temporarily disable git SSL verification
      steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set APP_VERSION Output 
        id: app_version
        run: echo "APP_VERSION=$(cat ./build.gradle | grep 'version =' | cut -d "=" -f 2 | tr -d "'" | xargs)" >> "$GITHUB_OUTPUT"
      - name: Set up JDK 21 & Cache Gradle
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Build and Analyse
#        run: gradle clean build test jacocoTestReport jacocoTestCoverageVerification sonar cyclonedxBom dependencies -info --scan -PignoreFailures=true --write-locks --continue
        run: ./gradlew clean compileJava compileTestJava build -x test cyclonedxBom dependencies -info --stacktrace --write-locks
      - name: Upload Compiled Classes and Build Directory
        uses: actions/upload-artifact@v4
        with:
          name: compiled-project
          path: build
          retention-days: 1
    test-code:
      name: Run Tests
      runs-on: ${{ fromJson(inputs.target-runner) }} 
      needs: Build
      env:
        NODE_TLS_REJECT_UNAUTHORIZED: '0'   # temporarily disable Node TLS checks
        GIT_SSL_NO_VERIFY: 'true'           # temporarily disable git SSL verification
      steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Uses native VM caching mapped directly to the project build files
      - name: Set up JDK 21 & Cache Gradle
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Download Compiled Project
        uses: actions/download-artifact@v4
        with:
          name: compiled-project
          path: build
      - name: Run Tests and Coverage
        run: ./gradlew test jacocoTestReport jacocoTestCoverageVerification -PignoreFailures=true -info --stacktrace --continue # 
        continue-on-error: true
# HTML test report	build/reports/tests/test/index.html
# JUnit XML results	build/test-results/test/
# JaCoCo HTML coverage	build/reports/jacoco/test/html/index.html
# JaCoCo XML coverage	build/reports/jacoco/test/jacocoTestReport.xml
      - name: Upload Junit Test Results
        uses: actions/upload-artifact@v4
        with:
          name: junit-test-results
          path: build/test-results/test/
          retention-days: 1
      - name: Publish Test Report to GitHub
        uses: dorny/test-reporter@v1
        with:
          name: junit-test-results
          path: '*.xml'
          reporter: jest-junit
          fail-on-empty: false
          list-suites: all
          list-tests: all
          use-actions-summary: true
      - name: Upload JaCoCo HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: build/reports/jacoco/test/html
          retention-days: 1
      - name: Upload HTML Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: build/reports/jacoco/test/html
          retention-days: 1
      # - name: Copy Sample Test Report 
      #   run: mkdir -p build/test-results/sample && cp -a junit-example.xml build/test-results/sample/
      # - name: Upload Test Report files
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: unit-test-report
      #     path: build/test-results/sample/
      # - name: Publish Test Report To GitHub
      #   uses: dorny/test-reporter@v2
      #   with:
      #     artifact: unit-test-report  # artifact name
      #     name: unit-test-report                  # Name of the check run which will be created
      #     path: '*.xml'                     # Path to test results (inside artifact .zip)
      #     reporter: jest-junit              # Format of test results
      #     fail-on-error: 'false'


    sonar-scan:
        name: SonarQube Scan
        runs-on: ${{ fromJson(inputs.target-runner) }} 
        needs: test-code
        if: ${{ always() }}
        env:
          NODE_TLS_REJECT_UNAUTHORIZED: '0'   # temporarily disable Node TLS checks
          GIT_SSL_NO_VERIFY: 'true'           # temporarily disable git SSL verification
        steps:
          - name: Check out repository
            uses: actions/checkout@v4
            with:
              fetch-depth: 0
          - name: Set up JDK 21 & Cache Gradle
            uses: actions/setup-java@v4
            with:
              java-version: '21'
              distribution: 'temurin'
              cache: 'gradle'
          - name: Download Project Reports and Binaries
            uses: actions/download-artifact@v4
            with:
              name: test-and-coverage-reports
              path: build/
          - name: Execute Sonar Scan
            env:
              SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            run: |
              ./gradlew sonar -info --stacktrace --debug
          # The final standalone step that blocks the pipeline if rules fail
          - name: Verify SonarQube Quality Gate Status
            uses: sonarsource/sonarqube-quality-gate-action@v1.2.0
            with:
              scanMetadataReportFile: build/sonar/report-task.txt
            env:
              SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              NODE_TLS_REJECT_UNAUTHORIZED: "0" 
              SONAR_HOST_URL: "http://10.0.2.15:9300"
          - name: Publish to Step Summary
            run: |
              cat build/sonar/report-task.txt >> $GITHUB_STEP_SUMMARY
    # Unit_Test:
    #   name: Unit_Test
    #   runs-on: ${{ fromJson(inputs.target-runner) }} 
    #   needs: [Build]
    #   container:
    #     image: gradle:9.6.1-jdk21
        # options: --user 1000:1000
    #   steps:
    #   - name: Checkout
    #     uses: actions/checkout@v4
    #   - name: Run Unit Tests
    #     run: gradle test --no-daemon
    #   - name: Copy Sample Test Report 
    #     run: mkdir -p build/test-results/sample && cp -a junit-example.xml build/test-results/sample/
    #   - name: Upload Test Report files
    #     uses: actions/upload-artifact@v4
    #     with:
    #       name: unit-test-report
    #       path: build/test-results/sample/
    #   - name: Publish Test Report To GitHub
    #     uses: dorny/test-reporter@v2
    #     with:
    #       artifact: unit-test-report  # artifact name
    #       name: unit-test-report                  # Name of the check run which will be created
    #       path: '*.xml'                     # Path to test results (inside artifact .zip)
    #       reporter: jest-junit              # Format of test results
    #       fail-on-error: 'false'
    # - uses: tiacsys/clean-after-action@v3
    # Docker_Push:
    #   name: Docker Push
    #   runs-on: ${{ fromJson(inputs.target-runner) }} 
    #   permissions:
    #     id-token: write # This is required for requesting the JWT for OIDC auth to AWS
    #     contents: read  # Required for checkout
    #   needs: Build
    #   steps:
    #   - name: Checkout
    #     uses: actions/checkout@v4
    #     with:
    #       clean: true
    #   - name: "Configure AWS Credentials - Action for GitHub Actions"
    #     uses: aws-actions/configure-aws-credentials@v4
    #     with:
    #       aws-region: ap-southeast-2 
    #       role-to-assume: arn:aws:iam::865983312994:role/github-actions-role
    #   - name: Verify AWS Identity
    #     run: |
    #       aws sts get-caller-identity
    #       aws s3 ls
    #   - name: Download build artifact
    #     uses: actions/download-artifact@v4
    #     with:
    #       name: ${{ env.build-artifact-key }}
    #       path: build-artefact/
    #   - name: Login to Amazon ECR
    #     id: login-ecr
    #     uses: aws-actions/amazon-ecr-login@v1
    #   - name: Docker Build 
    #     id: Docker-Build 
    #     env:
    #       ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
    #       APP_VERSION: ${{ needs.Build.outputs.APP_VERSION }}
    #     run: |
    #       echo "BRANCH_NAME_ESCAPED=$( echo ${{ github.ref_name }} | tr "/" _  )" >> $GITHUB_ENV
    #       docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }} -t $ECR_REGISTRY/$ECR_REPOSITORY:$APP_VERSION -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ env.APP_VERSION }}.${{ github.run_number }} .
    #       docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ env.APP_VERSION }}
    #       docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ env.APP_VERSION }}.${{ github.run_number }}
    #       docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}
    #       echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}" >> $GITHUB_OUTPUT
    #     working-directory: build-artefact/
    #   - uses: tiacsys/clean-after-action@v3
    # Tag:
    #   name: Tag
    #   runs-on: ubuntu-24.04
    #   permissions:
    #     contents: write
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
    #   needs: [Build, Docker_Push]
    #   steps:
    #   - uses: actions/checkout@v4
    #     with:
    #       clean: true
    #   - name: Git Tag 
    #     id: tag_version
    #     uses: mathieudutour/github-tag-action@v6.2
    #     with:
    #       release_branches: "release.*"
    #       github_token: ${{ env.GITHUB_TOKEN }}
    #       custom_tag: ${{ needs.Build.outputs.APP_VERSION }}.${{ github.run_number }}
    #   - uses: tiacsys/clean-after-action@v3