name: Java Application - Build
run-name: ${{ github.ref_name }}-${{ github.run_number }}

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true
      # GH_TOKEN:
      #   required: true       

env:
  RUNNER_DEFAULT: ubuntu-latest

defaults:
  run:
    shell: bash
      # runs-on:
      #   group: Build 
      #   labels: ubuntu

env:
  AWS_REGION: ap-southeast-2                   # set this to your preferred AWS region, e.g. us-west-1
  build-artifact-key: app-${{ github.sha }}
  ECR_REPOSITORY: java-application           # set this to your Amazon ECR repository name

jobs:
    Build:
      name: Build
      runs-on: ${{ env.RUNNER_DEFAULT }}
      outputs:
        APP_VERSION: ${{ steps.app_version.outputs.APP_VERSION }}
      container:
        image: gradle:jdk21
      steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set APP_VERSION Output 
        id: app_version
        run: echo "APP_VERSION=$(cat ./gradle.properties | grep version | cut -d "=" -f 2)" >> "$GITHUB_OUTPUT"
      - name: Build with Gradle
        run: gradle build test
        # - name: Simulating Gradle Build
      #   run: echo "hello" && mkdir -p app/build/libs/ && touch app/build/libs/java_application.jar
      - name: Build with Gradle
        run: gradle build test
      - name: Upload build files
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.build-artifact-key }}
          path: app/build/libs
      - name: Copy Sample Junit Report 
        run: cp -p app/junit-example.xml app/build/test-results/test/
      - name: Upload Test Report files
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-report
          path: app/build/test-results/test/
      - name: Publish Test Report To GitHub
        uses: dorny/test-reporter@v2
        with:
          artifact: unit-test-report  # artifact name
          name: unit-test-report                  # Name of the check run which will be created
          path: 'junit-example.xml'                     # Path to test results (inside artifact .zip)
          reporter: jest-junit              # Format of test results
    Push:
      name: Push
      runs-on: ${{ env.RUNNER_DEFAULT }}
      # runs-on:
      #   group: Build 
      #   labels: ubuntu
      permissions:
        id-token: write # This is required for requesting the JWT for OIDC auth to AWS
      needs: Build
      steps:
      - name: Checkout
        uses: actions/checkout@v4
#         #################### Setup with OIDC. Refer to 1 hour in of the 3 hour lecturer
      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.aws-access-key-id || secrets.aws-access-key-id }}
      #     aws-secret-access-key: ${{ secrets.aws-secret-access-key || secrets.aws-secret-access-key}}
      #     aws-region: ${{ env.AWS_REGION }
      - name: "Configure AWS Credentials - Action for GitHub Actions"
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          aws-region: ap-southeast-2 
          role-to-assume: arn:aws:iam::865983312994:role/github-actions-role
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.build-artifact-key }}
          path: app/build/libs
      # - name: Show folder structure
      #   run: ls -R app/build
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Docker Build 
        id: Docker-Build 
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
          APP_VERSION: ${{ needs.Build.outputs.APP_VERSION }}
        run: |
          echo "BRANCH_NAME_ESCAPED=$( echo ${{ github.ref_name }} | tr "/" _  )" >> $GITHUB_ENV
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:$APP_VERSION -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ env.APP_VERSION }}.${{ github.run_number }} .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ env.APP_VERSION }}
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ env.APP_VERSION }}.${{ github.run_number }}
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG 
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
    # Tag:
    #   name: Tag
    #   runs-on: ubuntu-24.04
    #   permissions:
    #     contents: write
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GH_TOKEN || secrets.GH_TOKEN}}
    #   # runs-on:
    #   #   group: Build 
    #   #   labels: ubuntu
    #   needs: [Build, Push]
    #   steps:
    #   - uses: actions/checkout@v4
    #   - name: Git Tag 
    #     id: tag_version
    #     uses: mathieudutour/github-tag-action@v6.2
    #     with:
    #       release_branches: "release.*"
    #       github_token: ${{ env.GITHUB_TOKEN }}
    #       custom_tag: ${{ needs.Build.outputs.APP_VERSION }}.${{ github.run_number }}
  #   - uses: tiacsys/clean-after-action@v3        


  # - name: Dump GitHub context
      #   env:
      #     GITHUB_CONTEXT: ${{ toJson(github) }}
        # run: echo "$GITHUB_CONTEXT" 



