# Gradle executing the sonarqube scan is the recommended way for java projects. Running it via the build tool ensures that compiled .class binaries and test coverage reports (like JaCoCo) are properly recognized without requiring complex file mapping parameters
# https://stackoverflow.com/questions/77373748/unable-to-run-sonarqube-scan-for-my-java-repository-using-github-actions
# https://docs.sonarsource.com/sonarqube-server/10.8/devops-platform-integration/github-integration/adding-analysis-to-github-actions-workflow

name: Java Application - Scanning All
run-name: ${{ github.ref_name }}-${{ github.run_number }}

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      target-runner:
        required: true
        type: string
        
defaults:
  run:
    shell: bash

env:
  AWS_REGION: ap-southeast-2                   # set this to your preferred AWS region, e.g. us-west-1
  build-artifact-key: app-${{ github.sha }}
  ECR_REPOSITORY: java-application           # set this to your Amazon ECR repository name

concurrency:
  group: ${{ github.workflow }}-runner-${{ github.ref }}
  cancel-in-progress: false

jobs:
    Build:
      name: Build
      runs-on: ${{ fromJson(inputs.target-runner) }} 
      outputs:
        APP_VERSION: ${{ steps.app_version.outputs.APP_VERSION }}
      env:
        NODE_TLS_REJECT_UNAUTHORIZED: '0'   # temporarily disable Node TLS checks
        GIT_SSL_NO_VERIFY: 'true'           # temporarily disable git SSL verification
      steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set APP_VERSION Output 
        id: app_version
        run: echo "APP_VERSION=$(cat ./build.gradle | grep 'version =' | cut -d "=" -f 2 | tr -d "'" | xargs)" >> "$GITHUB_OUTPUT"
      - name: Java Build
        uses: frankbuttigieg1993-gmail/cicd/.github/actions/java/build@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}  
          sonar-token: ${{ secrets.SONAR_TOKEN }} 
    test-code:
      name: Run Tests
      runs-on: ${{ fromJson(inputs.target-runner) }} 
      needs: Build
      env:
        NODE_TLS_REJECT_UNAUTHORIZED: '0'   # temporarily disable Node TLS checks
        GIT_SSL_NO_VERIFY: 'true'           # temporarily disable git SSL verification
      steps:
      - name: Java Test
        uses: frankbuttigieg1993-gmail/cicd/.github/actions/java/test@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}  
          sonar-token: ${{ secrets.SONAR_TOKEN }} 
    # sonar-scan:
    #     name: SonarQube Scan & Gate Check
    #     runs-on: ${{ fromJson(inputs.target-runner) }} 
    #     needs: test-code
    #     env:
    #       NODE_TLS_REJECT_UNAUTHORIZED: '0'   # temporarily disable Node TLS checks
    #       GIT_SSL_NO_VERIFY: 'true'           # temporarily disable git SSL verification
    #     steps:
    #       - name: Sonar Scan Java Application
    #         uses: frankbuttigieg1993-gmail/cicd/.github/actions/sonar-scan@main
    #         with:
    #           github-token: ${{ secrets.GITHUB_TOKEN }}  
    #           sonar-token: ${{ secrets.SONAR_TOKEN }} 
    # DependencyCheck:
    #   name: DependencyCheck
    #   runs-on: ${{ fromJson(inputs.target-runner) }} 
    #   needs: Build
    #   steps:
    # - name: Dependency Check
    #   uses: frankbuttigieg1993-gmail/cicd/.github/actions/dependency-check@main
    #   with:
    #     github-token: ${{ secrets.GITHUB_TOKEN }}  
    #     sonar-token: ${{ secrets.SONAR_TOKEN }} 
    CycloneDX_SBOM:
      name: CycloneDX_SBOM
      runs-on: ${{ fromJson(inputs.target-runner) }} 
      needs: [Build]
      steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download Build Artefact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: .
      # - name: Setup Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: '24'
      # - name: Verify Node and NPM 
      #   run: | 
      #     node -v
      #     npm -v
      # - name: Install CycloneDX CLI
      #   run: |
      #     CDX_VERSION="v0.29.1"
      #     curl -L \
      #       -o cyclonedx-linux-x64 \
      #       "https://github.com/CycloneDX/cyclonedx-cli/releases/download/${CDX_VERSION}/cyclonedx-linux-x64"
      #     chmod +x cyclonedx-linux-x64
      #     sudo mv cyclonedx-linux-x64 /usr/local/bin/cyclonedx
      #     cyclonedx --version
      # - name: Convert JSON SBOM to HTML
      #   run: |
      #     # The official CLI uses the convert command to output alternative layouts
      #     cyclonedx convert --input-file build/reports/cyclonedx/bom.json --output-file build/reports/cyclonedx/bom.html
      - name: Convert JSON SBOM to HTML
        run: |
          python trivy/sunshine.py -i build/reports/cyclonedx/bom.json -o build/reports/cyclonedx/bom.html
      - name: Publish CycloneDX BOM Files
        uses: actions/upload-artifact@master
        with:
            name: cyclone-bom-reports
            path: | 
             build/reports/cyclonedx/bom.json
             build/reports/cyclonedx/bom.html
            retention-days: 1
      - uses: tiacsys/clean-after-action@v3
        if: always()
#     Trivy:
#       name: Trivy
#       runs-on: ${{ fromJson(inputs.target-runner) }} 
#       needs: [Build]
#       permissions:
#         id-token: write # This is required for requesting the JWT for OIDC auth to AWS
#         contents: read  # Required for checkout
#       env:
#         NODE_TLS_REJECT_UNAUTHORIZED: "0" # Disables SSL strictness for Node tools - addresses trivy certificate issue behind CGI corporate proxy
#         GIT_SSL_NO_VERIFY: "true"         # Disables SSL strictness for Git fetches
#       steps:
#       - name: Checkout
#         uses: actions/checkout@v4
#       # Trivy needs the lock file for an accurate scan including transitive dependencies. Gradle generated this file so the transitive dependencies are included. 
#       - name: Download Build Artefact
#         uses: actions/download-artifact@v4
#         with:
#           name: build
#           path: .
#       - name: Confirm Existence of the Gradle Lock File
#         run: | 
#          printenv | grep GIT
#          ls -alrt gradle.lockfile

#       # - name: Setup Trivy (preinstalled) ## Needed for self hosted VM
#       #   uses: aquasecurity/trivy-action@v0.72.0
#       #   with:
#       #     path: /opt/trivy
#       #     key: trivy-binary-v0.72.0-Linux-X64
#       #     enableCrossOsArchive: false
#       #     fail-on-cache-miss: false
#       - name: Cache Gradle and Maven
#         uses: actions/cache@v4
#         with:
#           path: |
#             ~/.gradle/caches
#             ~/.gradle/wrapper
#             ~/.m2/repository
#           key: ${{ runner.os }}-deps-${{ hashFiles('**/*.gradle*', '**/gradle.lockfile', '**/settings.gradle*') }}

#       - name: Warm dependency cache
#         run: ./gradlew --no-daemon dependencies --write-locks build -x test
#         # or the smallest step that fully resolves dependencies

#       - name: Write Trivy config for offline Java scanning
#         run: |
#           mkdir -p .github
#           cat > .github/trivy-scan.yaml <<'EOF'
#           scan:
#             offline: true
#           EOF

#       - name: Trivy Scan Source Code Table
#         uses: aquasecurity/trivy-action@master
#         env:
#           TRIVY_INCLUDE_DEV_DEPS: "true" ### any CLI OPtion not supported by the github action can be passed as an environemnt variable
#           NODE_TLS_REJECT_UNAUTHORIZED: "0" # Disables SSL strictness for Node tools - addresses trivy certificate issue behind CGI corporate proxy
#           GIT_SSL_NO_VERIFY: "true"         # Disables SSL strictness for Git fetches
#           TRIVY_CACHE_DIR: ~/.cache/trivy
#         with:
#           scan-type: 'fs'
#           scan-ref: '.' # should be where build.gradle lives and trivy automatically scans dependnecices
#           format: 'table'
#           # output: 'reports/trivy-report.txt'
# #          exit-code: '1' # Fails the pipeline if vulnerabilities match criteria
#           ignore-unfixed: true
#           severity: 'CRITICAL,HIGH'
#           scanners: "vuln,misconfig,license"
#           trivy-config: .github/trivy-scan.yaml
#           timeout: 20m

#       - name: Trivy Scan Source Code 
#         uses: aquasecurity/trivy-action@v0.36.0
#         env: 
#           TRIVY_INCLUDE_DEV_DEPS: "true" ### any CLI Option not supported by the github action can be passed as an environemnt variable
#           NODE_TLS_REJECT_UNAUTHORIZED: "0" # Disables SSL strictness for Node tools - addresses trivy certificate issue behind CGI corporate proxy
#           GIT_SSL_NO_VERIFY: "true"         # Disables SSL strictness for Git fetches
#           TRIVY_CACHE_DIR: ~/.cache/trivy
#         with:
#           scan-type: 'fs' 
#           scan-ref: '.'
#           format: 'template'
#           template: '@${{ github.workspace }}/trivy/html_template.tpl'
#           scanners: "vuln,misconfig,license"
#           ignore-unfixed: true
#           output: 'build/reports/trivy-srccode-report.html'
#           trivy-config: .github/trivy-scan.yaml
#           timeout: 20m

#       - name: Publish Trivy Scan Source Code HTML Report
#         uses: actions/upload-artifact@v4
#         with:
#           name: trivy-srccode-report
#           path: build/reports/trivy-srccode-report.html
#           retention-days: 30
#       - name: Trivy Scan JAR 
#         uses: aquasecurity/trivy-action@v0.36.0
#         env: 
#           TRIVY_INCLUDE_DEV_DEPS: "true" ### any CLI Option not supported by the github action can be passed as an environemnt variable
#           NODE_TLS_REJECT_UNAUTHORIZED: "0" # Disables SSL strictness for Node tools - addresses trivy certificate issue behind CGI corporate proxy
#           GIT_SSL_NO_VERIFY: "true"         # Disables SSL strictness for Git fetches
#           TRIVY_CACHE_DIR: ~/.cache/trivy
#         with:
#           scan-type: 'rootfs'
#           scan-ref: 'build/libs/env-printer-springboot-project-1.0.0.jar' # Explicit path to your JAR file
#           format: 'template'
#           template: '@${{ github.workspace }}/trivy/html_template.tpl'
#           scanners: "vuln,misconfig,license"
#           ignore-unfixed: true
#           output: 'build/reports/trivy-jar-report.html'
#           trivy-config: .github/trivy-scan.yaml
#           timeout: 20m          

#       - name: Publish Trivy Scan JAR HTML Report
#         uses: actions/upload-artifact@v4
#         with:
#           name: trivy-jar-report
#           path: build/reports/trivy-jar-report.html
#           retention-days: 30
#       - name: Docker Build 
#         id: Docker-Build 
#         run: |
#           echo "BRANCH_NAME_ESCAPED=$( echo ${{ github.ref_name }} | tr "/" _  )" >> $GITHUB_ENV
#           docker build -t java-application:${{ github.sha }} .
#         #  docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ env.APP_VERSION }}
#         #  docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ env.APP_VERSION }}.${{ github.run_number }}
#         #  docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}
#         #  echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}" >> $GITHUB_OUTPUT
#       - name: Trivy Docker Image 
#         uses: aquasecurity/trivy-action@v0.36.0
#         env: 
#           TRIVY_INCLUDE_DEV_DEPS: "true" ### any CLI Option not supported by the github action can be passed as an environemnt variable
#           NODE_TLS_REJECT_UNAUTHORIZED: "0" # Disables SSL strictness for Node tools - addresses trivy certificate issue behind CGI corporate proxy
#           GIT_SSL_NO_VERIFY: "true"         # Disables SSL strictness for Git fetches
#           TRIVY_CACHE_DIR: ~/.cache/trivy
#         with:
#           scan-type: 'image' 
#           image-ref: 'java-application:${{ github.sha }}'
#           format: 'template'
#           template: '@${{ github.workspace }}/trivy/html_template.tpl'
#           scanners: "vuln,misconfig,license"
#           ignore-unfixed: true
#           output: 'build/reports/trivy-dockerimage-report.html'
#           trivy-config: .github/trivy-scan.yaml
#           timeout: 20m
#       - name: Trivy Scan Docker Image HTML Report
#         uses: actions/upload-artifact@v4
#         with:
#           name: trivy-dockerimage-report
#           path: build/reports/trivy-dockerimage-report.html
#           retention-days: 30
#       - name: Trivy Webgoat Docker Image SCan
#         run: |
#           curl -LO https://github.com/WebGoat/WebGoat/releases/download/v2025.3/webgoat-2025.3.jar
#       - name: Trivy Scan JAR - Webgoat 
#         uses: aquasecurity/trivy-action@v0.36.0
#         env: 
#           TRIVY_INCLUDE_DEV_DEPS: "true" ### any CLI Option not supported by the github action can be passed as an environemnt variable
#           NODE_TLS_REJECT_UNAUTHORIZED: "0" # Disables SSL strictness for Node tools - addresses trivy certificate issue behind CGI corporate proxy
#           GIT_SSL_NO_VERIFY: "true"         # Disables SSL strictness for Git fetches
#           TRIVY_CACHE_DIR: ~/.cache/trivy
#         with:
#           scan-type: 'rootfs'
#           scan-ref: 'webgoat-2025.3.jar' # Explicit path to your JAR file
#           format: 'template'
#           template: '@${{ github.workspace }}/trivy/html_template.tpl'
#           scanners: "vuln,misconfig,license"
#           ignore-unfixed: true
#           output: 'build/reports/trivy-webgoat-jar-report.html'
#           trivy-config: .github/trivy-scan.yaml

#       - name: Trivy Scan JAR HTML Report - Webgoat
#         uses: actions/upload-artifact@v4
#         with:
#           name: trivy-webgoat-jar-report
#           path: build/reports/trivy-webgoat-jar-report.html
#           retention-days: 30
#       - name: Scan Reports 
#         uses: actions/upload-artifact@v4
#         with:
#           name: scan-reports
#           path: build/reports/
#           retention-days: 30
#       - uses: tiacsys/clean-after-action@v3
#         if: always()
    semgrep_scan:
      name: semgrep/ci
      runs-on: ${{ fromJson(inputs.target-runner) }} 
      needs: [Build]
      env:
        SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }} 
        HOME: ${{ github.workspace }}    # Points Semgrep to the workspace directory it already has access to
        NODE_TLS_REJECT_UNAUTHORIZED: "0" # Disables SSL strictness for Node tools - addresses trivy certificate issue behind CGI corporate proxy
        GIT_SSL_NO_VERIFY: "true"         # Disables SSL strictness for Git fetches
      # Skip any PR created by dependabot to avoid permission issues:
      if: (github.actor != 'dependabot[bot]')
      permissions:
        # required for all workflows
        security-events: write
        # only required for workflows in private repositories
        actions: read
        contents: read
      steps:
        # Fetch project source with GitHub Actions Checkout.
        - name: Checkout repository
          uses: actions/checkout@v4
        # Gradle generated this file so the transitive dependencies are included. Semgrep scans the transitive dependencies better when it has the gradle lock file
        - name: Download Gradle Lock File
          uses: actions/download-artifact@v4
          with:
            name: build
            path: .
        - name: Confirm Existence of the Gradle Lock File
          run: ls -alrt gradle.lockfile
        # - name: Semgrep AppSec Platform Analysis
        #   uses: docker://returntocorp/semgrep:1.163.0-nonroot
        #   with: 
        #     args: semgrep ci --supply-chain --code --metrics=off --sarif --sarif-output=semgrep.sarif  --no-suppress-errors
        # - name: Write corporate CA cert
        #   run: |
        #     echo "$CORP_CA_B64" | base64 -d > corp-ca.pem
        #   env:
        #     CORP_CA_B64: ${{ secrets.CORP_CA_B64 }}
        - name: Write corporate CA cert
          run: |
            cp -p /home/ubuntu/zscaler-crt.crt corp-ca.pem
        - name: Confirm Gradle Lock File
          run: ls -alrt gradle.lockfile
# -w overrides the working directory for the container. 
# This is scanning everything inside the repository since $pwd is mapped to /src and we are configuring the scanner to look at /src
        - name: Semgrep AppSec Platform Analysis
          run: |
            docker run --rm \
              -e SEMGREP_APP_TOKEN="${SEMGREP_APP_TOKEN}" \
              -e SSL_CERT_FILE=/certs/corp-ca.pem \
              -e REQUESTS_CA_BUNDLE=/certs/corp-ca.pem \
              -v "$PWD:/src" \
              -v "$PWD/corp-ca.pem:/certs/corp-ca.pem:ro" \
              -w /src \   
              returntocorp/semgrep:1.163.0-nonroot \
              semgrep ci --supply-chain --code --metrics=off --sarif --sarif-output=semgrep.sarif --no-suppress-errors
        # ChatGPT recommended the following if I'm not using the Semgrep AppSec Platform: semgrep ci --supply-chain --code --oss-only --metrics=off 
        # run: semgrep scan -q --sarif --config auto ./src --time --sarif-output=semgrep-results.sarif
        - name: Semgrep AppSec Platform Artefact
          uses: actions/upload-artifact@v4
          with:
            name: semgrep-scan-results
            path: semgrep.sarif
        - name: Upload Semgrep AppSec Platform to the GitHub Security Dashboard
          uses: github/codeql-action/upload-sarif@v4
          with:
            sarif_file: semgrep.sarif
          if: always()
        # - name: Run Local Scan
        #   uses: docker://returntocorp/semgrep:1.163.0-nonroot
        #   with: 
        #     args: semgrep scan --config auto --error --json --json-output=semgrep-local-scan-results.json --sarif --sarif-output=semgrep-local-scan-results.sarif --no-suppress-errors
        - name: Run Local Scan
          run: |
            docker run --rm \
              -e SEMGREP_APP_TOKEN="${SEMGREP_APP_TOKEN}" \
              -e SSL_CERT_FILE=/certs/corp-ca.pem \
              -e REQUESTS_CA_BUNDLE=/certs/corp-ca.pem \
              -v "$PWD:/src" \
              -v "$PWD/corp-ca.pem:/certs/corp-ca.pem:ro" \
              -w /src \
              returntocorp/semgrep:1.163.0-nonroot \
              semgrep scan --config auto --error --json --json-output=semgrep-local-scan-results.json --sarif --sarif-output=semgrep-local-scan-results.sarif --no-suppress-errors src
        - name: Upload Semgrep Local Scan to the GitHub Security Dashboard
          uses: github/codeql-action/upload-sarif@v4
          with:
            sarif_file: semgrep-local-scan-results.sarif 
          if: always()
        - name: Generate HTML Reports
          run: |
            python3 trivy/parse-semgrep.py --input semgrep.sarif --output semgrep-report.html --project-name "Java Application SemGrep AppSec" --only INFO,WARNING,ERROR
            python3 trivy/parse-semgrep.py --input semgrep-local-scan-results.json --output semgrep-local-scan-report.html --project-name "Java Application SemgGrep Local" --only INFO,WARNING,ERROR
        - name: Publish Semgrep AppSet HTML Report
          uses: actions/upload-artifact@v4
          with:
            name: semgrep-appsec-report
            path: semgrep-report.html
            retention-days: 2
        - name: Publish Semgrep Local Scan HTML Report
          uses: actions/upload-artifact@v4
          with:
            name: semgrep-local-scan-report
            path: semgrep-local-scan-report.html
            retention-days: 2
        - uses: tiacsys/clean-after-action@v3
          if: always()
    # Docker_Push:
    #   name: Docker Push
    #   runs-on: ${{ fromJson(inputs.target-runner) }} 
    #   permissions:
    #     id-token: write # This is required for requesting the JWT for OIDC auth to AWS
    #     contents: read  # Required for checkout
    #   needs: Build
    #   steps:
    #   - name: Checkout
    #     uses: actions/checkout@v4
    #     with:
    #       clean: true
    #   - name: "Configure AWS Credentials - Action for GitHub Actions"
    #     uses: aws-actions/configure-aws-credentials@v4
    #     with:
    #       aws-region: ap-southeast-2 
    #       role-to-assume: arn:aws:iam::865983312994:role/github-actions-role
    #   - name: Verify AWS Identity
    #     run: |
    #       aws sts get-caller-identity
    #       aws s3 ls
    #   - name: Download Build Artefact
    #     uses: actions/download-artifact@v4
    #     with:
    #       name: build
    #       path: .
    #   - name: Login to Amazon ECR
    #     id: login-ecr
    #     uses: aws-actions/amazon-ecr-login@v1
    #   - name: Docker Build 
    #     id: Docker-Build 
    #     env:
    #       ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
    #       APP_VERSION: ${{ needs.Build.outputs.APP_VERSION }}
    #     run: |
    #       echo "BRANCH_NAME_ESCAPED=$( echo ${{ github.ref_name }} | tr "/" _  )" >> $GITHUB_ENV
    #       docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }} -t $ECR_REGISTRY/$ECR_REPOSITORY:$APP_VERSION -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ env.APP_VERSION }}.${{ github.run_number }} .
    #       docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ env.APP_VERSION }}
    #       docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ env.APP_VERSION }}.${{ github.run_number }}
    #       docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}
    #       echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}" >> $GITHUB_OUTPUT
    #   - uses: tiacsys/clean-after-action@v3
    # Tag:
    #   name: Tag
    #   runs-on: ubuntu-24.04
    #   permissions:
    #     contents: write
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
    #   needs: [Build, Docker_Push]
    #   steps:
    #   - uses: actions/checkout@v4
    #     with:
    #       clean: true
    #   - name: Git Tag 
    #     id: tag_version
    #     uses: mathieudutour/github-tag-action@v6.2
    #     with:
    #       release_branches: "release.*"
    #       github_token: ${{ env.GITHUB_TOKEN }}
    #       custom_tag: ${{ needs.Build.outputs.APP_VERSION }}.${{ github.run_number }}
    #   - uses: tiacsys/clean-after-action@v3