name: 'Semgrep Scan'
description: 'Semgrep Scan'

inputs:
  github-token:
    description: 'The github token'
    required: true
  SEMGREP_APP_TOKEN:
    description: 'The SEMGREP_APP_TOKEN'
    required: true
 
runs:
  using: 'composite'
  steps:
        # Fetch project source with GitHub Actions Checkout.
        - name: Checkout repository
          uses: actions/checkout@v6
        # Gradle generated this file so the transitive dependencies are included. Semgrep scans the transitive dependencies better when it has the gradle lock file
        - name: Download Build Artefact
          uses: actions/download-artifact@v8
          with:
            name: build
            path: .
        # - name: Semgrep AppSec Platform Analysis
        #   uses: docker://returntocorp/semgrep:1.163.0-nonroot
        #   with: 
        #     args: semgrep ci --supply-chain --code --metrics=off --sarif --sarif-output=semgrep.sarif  --no-suppress-errors
        # - name: Write corporate CA cert
        #   run: |
        #     echo "$CORP_CA_B64" | base64 -d > corp-ca.pem
        #   env:
        #     CORP_CA_B64: ${{ secrets.CORP_CA_B64 }}
        - name: Bootstrap 
          run: |
            mkdir -p build/reports/semgrep
          shell: bash 
# -w overrides the working directory for the container. 
# This is scanning everything inside the repository since $pwd is mapped to /src and we are configuring the scanner to look at /src
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: "3.11"

        - name: Install Semgrep
          run: |
            python -m pip install --upgrade pip
            python -m pip install semgrep==1.163.0
            python -m pip install Jinja2
          shell: bash          

        # ChatGPT recommended the following if I'm not using the Semgrep AppSec Platform: semgrep ci --supply-chain --code --oss-only --metrics=off 
        # run: semgrep scan -q --sarif --config auto ./src --time --sarif-output=semgrep-results.sarif

        # - name: Run Local Scan
        #   env:
        #     SEMGREP_APP_TOKEN: ${{ inputs.SEMGREP_APP_TOKEN }}
        #     SSL_CERT_FILE: ${{ github.workspace }}/corp-ca.pem
        #     REQUESTS_CA_BUNDLE: ${{ github.workspace }}/corp-ca.pem
        #   run: |
        #     semgrep scan \
        #       --config auto \
        #       --sarif \
        #       --sarif-output=build/reports/semgrep/semgrep-local-scan-results.sarif
        #   shell: bash

        - name: Run Local Scan
          env:
            SEMGREP_APP_TOKEN: ${{ inputs.SEMGREP_APP_TOKEN }}
          run: |
            echo "========================================"
            echo "Starting Semgrep Local Scan"
            echo "========================================"

            /usr/bin/time -v semgrep scan \
              --config auto \
              --sarif \
              --sarif-output=build/reports/semgrep/semgrep-local-scan-results.sarif 
              src/

            echo "========================================"
            echo "Finished Semgrep Local Scan"
            echo "========================================"
          shell: bash

        - name: Upload Semgrep Local Scan to the GitHub Security Dashboard
          uses: github/codeql-action/upload-sarif@v4
          with:
            sarif_file: build/reports/semgrep/semgrep-local-scan-results.sarif 
          if: always()
        - name: Generate HTML Reports
          run: |
            python3 trivy/parse-semgrep-sarif.py --input build/reports/semgrep/semgrep-local-scan-results.sarif --output build/reports/semgrep/semgrep-local-report.html --project-name "Java Application SemGrep Local Scan"
#            python3 trivy/parse-semgrep.py --input semgrep-local-scan-results.json --output semgrep-local-scan-report.html --project-name "Java Application SemgGrep Local" --only INFO,WARNING,ERROR
          shell: bash 
        - name: Publish Semgrep Reports 
          uses: actions/upload-artifact@v7
          with:
            name: semgrep-local-scan
            path: build/reports/semgrep/
            retention-days: 1
        - uses: tiacsys/clean-after-action@v4
          if: always()